### ISSUE TITLE
Error, not able to contact my server

### ISSUE THREAD

**Issue by piejanssens** [dersphere/XBMC-CouchPotato-Manager#1]
On LAN
Not using reverse proxy
Not using HTTPS

I'm not exactly sure if the following log messages are from the error, but looks like the addon is not saving my settings and not using them either...

18:04:17 T:140137098884864  NOTICE: -->Python Interpreter Initialized<--
18:04:17 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:04:17 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:04:36 T:140137098884864  NOTICE: Thread XBPyThread start, auto delete: false
18:04:36 T:140137098884864  NOTICE: -->Python Interpreter Initialized<--
18:04:36 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:04:36 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:04:39 T:140137098884864  NOTICE: Thread XBPyThread start, auto delete: false
18:04:39 T:140137098884864  NOTICE: -->Python Interpreter Initialized<--
18:04:39 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:04:39 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:04:41 T:140137098884864  NOTICE: Thread XBPyThread start, auto delete: false
18:04:41 T:140137098884864  NOTICE: -->Python Interpreter Initialized<--
18:04:42 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:04:42 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:04:51 T:140137098884864  NOTICE: Thread Background Loader start, auto delete: false
18:04:52 T:140136545425152  NOTICE: Previous line repeats 1 times.
18:04:52 T:140136545425152  NOTICE: Thread XBPyThread start, auto delete: false
18:04:53 T:140136545425152  NOTICE: -->Python Interpreter Initialized<--
18:04:53 T:140136545425152  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:04:53 T:140136545425152  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:04:56 T:140138291668800  NOTICE: NFS is idle. Closing the remaining connections.
18:05:22 T:140137098884864  NOTICE: Thread XBPyThread start, auto delete: false
18:05:22 T:140137098884864  NOTICE: -->Python Interpreter Initialized<--
18:05:22 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:05:22 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:05:32 T:140137098884864  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:05:32 T:140137098884864  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:05:33 T:140136545425152  NOTICE: [CouchPotatoApi]: u'connect: hostname="localhost" port="5050" use_https="False" username="" api_key="True" url_base=""'
18:05:33 T:140136545425152  NOTICE: [CouchPotatoApi]: u'_get_api_key: username=""'
18:05:35 T:140138291668800   ERROR: GetDirectory - Error getting plugin://plugin.video.couchpotato_manager/?content_type=executable
18:05:35 T:140138291668800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.couchpotato_manager/?content_type=executable) failed

**Comment by dersphere** [comment]
Username (and maybe password) is not set.
Go to add-on settings, set username/password _press OK_ and please try again.

**Comment by piejanssens** [comment]
When initially selecting the default quality you should use the textbox values in stead of the stored settings..

Verstuurd vanaf mijn iPhone

Op 20-apr.-2013 om 18:54 heeft Tristan Fischer notifications@github.com het volgende geschreven:

**Comment by dersphere** [comment]
What about your username not set problem?

**Comment by piejanssens** [comment]
Intially there are no settings stored.
The user opens the settings, enters his data and wants to select the default profile.
This is where the problem is, the default profile selection logic probably tries to use the settings stored, which do not exist yet because the OK button has not been pressed...

**Comment by dersphere** [comment]
Yes. Choosing default profile won't work unless you save (correct) user credentials. Nothing I can do to change that.

**Comment by piejanssens** [comment]
Do an extra save first, like you would when the user presses OK, when the user presses the button to select default profile...

**Comment by dersphere** [comment]
Like I already said, this isn't possible. The complete settings dialog is out of add-on API control.

**Comment by piejanssens** [comment]
Ok lol, you did not say that. But if that's true then this can be closed.

**Comment by dersphere** [comment]
That was what I meant with "won't work unless you save" ;)
Anyway, I will keep this in mind. Maybe I can add a visible note to avoid this.
