### ISSUE TITLE
api_key setting is missing from the settings dialog

### ISSUE THREAD

**Issue by Phally** [dersphere/XBMC-CouchPotato-Manager#3]
The only way to add an api_key is to edit settings.xml manually and reading the source code of the API lib to guess the correct name for it. It's not really user friendly ;)

**Comment by dersphere** [comment]
Why do you need to set the api_key manually?

**Comment by Phally** [comment]
CP runs on a different machine. It has an API key set for other machines connecting to it. Something like this: http://awesomescreenshot.com/0d21fkn18c (obviously i removed my api key). Without the API key CP simply says "Wrong API key used".

**Comment by dersphere** [comment]
Ok, you explained why in #4. Makes sense (in your exceptional case).

The easiest solution for you is adding the following line to `resources/settings.xml`:
`<setting id="api_key" type="text" label="API-Key" />`

Then you can manually fill in the api-key in the add-on settings dialog. The Add-on will first try this key - and only try to request a new one using username/password if that fails.

Please test this and report back.

**Comment by Phally** [comment]
Works perfectly!
