### ISSUE TITLE
No way to use HTTP basic authentication

### ISSUE THREAD

**Issue by Phally** [dersphere/XBMC-CouchPotato-Manager#4]
For CP I use a reverse proxy to https://example.com/couchpotato. However instead of using CP's built-in authentication I am using HTTP basic authentication from the webserver itself (easier to maintain and share).

So I tried to leave the username and password empty and use a hostname like this: username:password@example.com, but that failed unfortunately.

**Comment by dersphere** [comment]
I added the needed code to use basic-auth.
Please try this branch: https://github.com/dersphere/XBMC-CouchPotato-Manager/tree/advanced_settings

Or do the needed changes manually: https://github.com/dersphere/XBMC-CouchPotato-Manager/commit/32f021d19d9482e34eb9dc8cbb71f48ed7174301

(Please note that this commit also addresses #3)

**Comment by Phally** [comment]
Works like a charm. Thanks for this! The separated Advanced settings panel is a nice touch as well.

**Comment by dersphere** [comment]
Fine, I wanted to push a new version out today anyway.
